apiVersion: v1
kind: Service
metadata: 
  name: voguenest-api-service
  namespace: default
  labels:
    app: voguenest-api
    env: production
spec:
  type: ClusterIP
  selector:
    app: voguenest-api-pod
  ports:
    - port: 80
      targetPort: 3120

