pipeline {
    agent any

    environment {
        STRIPE_SECRET   = credentials('STRIPE_SECRET')
        SECRET          = credentials('SECRET')
        MONGODB_URL     = credentials('MONGODB_URL')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Prepare .env') {
            steps {
                dir('Deploy') {   
                    sh '''
                    cat > .env <<EOF
                        STRIPE_SECRET=${STRIPE_SECRET}
                        SECRET=${SECRET}
                        MONGODB_URL=${MONGODB_URL}
                        EOF
                    '''
                }
            }
        }

        stage('Build Images') {
            steps {
                dir('Deploy') {
                    sh 'docker compose build --no-cache'
                }
            }
        }

        stage('Start Services') {
            steps {
                dir('Deploy') {
                    sh 'docker compose up -d --force-recreate'
                }
            }
        }

        stage('Verify') {
            steps {
                dir('Deploy') {
                    sh 'docker compose ps'
                }
            }
        }

        stage('Cleanup .env') {
            steps {
                dir('Deploy') {
                    sh 'rm -f .env'
                }
            }
        }
    }
}
